---
# tasks file for ansible-openvswitch (Alpine specific)

- name: Install OpenVSwitch packages
  apk: name={{ item }} state=present update_cache=yes
  with_items: openvswitch_packages
  tags: openvswitch
