---
# tasks file for ansible-openvswitch (Ubuntu specific)

- name: Install OpenVSwitch packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: openvswitch_packages
  tags: openvswitch
